spring.application.name=auth-service
server.port=8080
spring.output.ansi.enabled=always

# JDBC - Primary (master) + Slave (replica) for read/write routing
spring.datasource.primary.driver-class-name=org.postgresql.Driver
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5433/quiz_app
spring.datasource.primary.username=admin
spring.datasource.primary.password=12345678

spring.datasource.slave.driver-class-name=org.postgresql.Driver
spring.datasource.slave.jdbc-url=jdbc:postgresql://localhost:5434/quiz_app
spring.datasource.slave.username=admin
spring.datasource.slave.password=12345678

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.leaseRenewalIntervalInSeconds:30
eureka.instance.leaseExpirationDurationInSeconds:90
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Hikari
spring.datasource.hikari.pool-name=QuizAppPool
spring.datasource.hikari.maximum-pool-size=10

# Logging
logging.level.org.postgresql=DEBUG
logging.level.com.example.base_module.datasource=INFO



