spring.application.name=service-registry
server.port=8761
spring.output.ansi.enabled=always

spring.cloud.client.hostname=localhost

#Eureka Server
eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enableSelfPreservation: true
eureka.server.evictionIntervalTimerInMs: 60000