spring.application.name=api-gateway

# Eureka URL inside Docker (overridden by env var too)
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# Instance identity inside Docker network
eureka.instance.hostname=api-gateway
eureka.instance.prefer-ip-address=false

