spring.application.name=question-service
server.port=8081
spring.output.ansi.enabled=always

# Eureka Client (để Gateway tìm được service)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
