spring.application.name=core-service
server.port=8081
spring.output.ansi.enabled=always
spring.threads.virtual.enabled=true
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/quiz_app
spring.datasource.username=admin
spring.datasource.password=12345678

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=20

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.leaseRenewalIntervalInSeconds=30
eureka.instance.leaseExpirationDurationInSeconds=90
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Hikari
spring.datasource.hikari.pool-name=QuizAppPool
spring.datasource.hikari.maximum-pool-size=20

# Logging
spring.jpa.show-sql=false
logging.level.org.postgresql=WARN

app.jwt.secret=q7Xv9Kp2ZL8sN4wFh3RjT6mYbD1cUe5A0GxVQzCkJrHnP9tS2Wf8B4yL6M

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
